//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerService.IServerService")]
    public interface IServerService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetHandlerConnectionString", ReplyAction="http://tempuri.org/IClientService/GetHandlerConnectionStringResponse")]
        System.Threading.Tasks.Task<string> GetHandlerConnectionStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/DownloadFile", ReplyAction="http://tempuri.org/IClientService/DownloadFileResponse")]
        System.Threading.Tasks.Task<byte[]> DownloadFileAsync(string fileNameAndExtension);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/UploadFile", ReplyAction="http://tempuri.org/IServerService/UploadFileResponse")]
        System.Threading.Tasks.Task<bool> UploadFileAsync(byte[] stream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/SetNextFileNameWithOverride", ReplyAction="http://tempuri.org/IServerService/SetNextFileNameWithOverrideResponse")]
        System.Threading.Tasks.Task SetNextFileNameWithOverrideAsync(string name, bool @override);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/SetNextFileNameWithoutOverride", ReplyAction="http://tempuri.org/IServerService/SetNextFileNameWithoutOverrideResponse")]
        System.Threading.Tasks.Task SetNextFileNameWithoutOverrideAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IServerServiceChannel : ServerService.IServerService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class ServerServiceClient : System.ServiceModel.ClientBase<ServerService.IServerService>, ServerService.IServerService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServerServiceClient() : 
                base(ServerServiceClient.GetDefaultBinding(), ServerServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ServerService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServerServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServerServiceClient.GetBindingForEndpoint(endpointConfiguration), ServerServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServerServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServerServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServerServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServerServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetHandlerConnectionStringAsync()
        {
            return base.Channel.GetHandlerConnectionStringAsync();
        }
        
        public System.Threading.Tasks.Task<byte[]> DownloadFileAsync(string fileNameAndExtension)
        {
            return base.Channel.DownloadFileAsync(fileNameAndExtension);
        }
        
        public System.Threading.Tasks.Task<bool> UploadFileAsync(byte[] stream)
        {
            return base.Channel.UploadFileAsync(stream);
        }
        
        public System.Threading.Tasks.Task SetNextFileNameWithOverrideAsync(string name, bool @override)
        {
            return base.Channel.SetNextFileNameWithOverrideAsync(name, @override);
        }
        
        public System.Threading.Tasks.Task SetNextFileNameWithoutOverrideAsync(string name)
        {
            return base.Channel.SetNextFileNameWithoutOverrideAsync(name);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ServerService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ServerService))
            {
                return new System.ServiceModel.EndpointAddress("http://www12.steenhoff.dk:4880/AdProgram/Service/Server Service/ServerService.svc" +
                        "");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServerServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ServerService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServerServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ServerService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ServerService,
        }
    }
}
