//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ad.Client.ClientService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientService.IClientService")]
    public interface IClientService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetHandlerConnectionString", ReplyAction="http://tempuri.org/IClientService/GetHandlerConnectionStringResponse")]
        string GetHandlerConnectionString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetHandlerConnectionString", ReplyAction="http://tempuri.org/IClientService/GetHandlerConnectionStringResponse")]
        System.Threading.Tasks.Task<string> GetHandlerConnectionStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/DownloadFile", ReplyAction="http://tempuri.org/IClientService/DownloadFileResponse")]
        System.IO.Stream DownloadFile(string fileNameAndExtension);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/DownloadFile", ReplyAction="http://tempuri.org/IClientService/DownloadFileResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DownloadFileAsync(string fileNameAndExtension);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientServiceChannel : Ad.Client.ClientService.IClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientServiceClient : System.ServiceModel.ClientBase<Ad.Client.ClientService.IClientService>, Ad.Client.ClientService.IClientService {
        
        public ClientServiceClient() {
        }
        
        public ClientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetHandlerConnectionString() {
            return base.Channel.GetHandlerConnectionString();
        }
        
        public System.Threading.Tasks.Task<string> GetHandlerConnectionStringAsync() {
            return base.Channel.GetHandlerConnectionStringAsync();
        }
        
        public System.IO.Stream DownloadFile(string fileNameAndExtension) {
            return base.Channel.DownloadFile(fileNameAndExtension);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DownloadFileAsync(string fileNameAndExtension) {
            return base.Channel.DownloadFileAsync(fileNameAndExtension);
        }
    }
}
