//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadUploadTesting.ServerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerService.IServerService")]
    public interface IServerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetHandlerConnectionString", ReplyAction="http://tempuri.org/IClientService/GetHandlerConnectionStringResponse")]
        string GetHandlerConnectionString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetHandlerConnectionString", ReplyAction="http://tempuri.org/IClientService/GetHandlerConnectionStringResponse")]
        System.Threading.Tasks.Task<string> GetHandlerConnectionStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/DownloadFile", ReplyAction="http://tempuri.org/IClientService/DownloadFileResponse")]
        System.IO.Stream DownloadFile(string fileNameAndExtension);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/DownloadFile", ReplyAction="http://tempuri.org/IClientService/DownloadFileResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DownloadFileAsync(string fileNameAndExtension);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/UploadFile", ReplyAction="http://tempuri.org/IServerService/UploadFileResponse")]
        bool UploadFile(System.IO.Stream stream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/UploadFile", ReplyAction="http://tempuri.org/IServerService/UploadFileResponse")]
        System.Threading.Tasks.Task<bool> UploadFileAsync(System.IO.Stream stream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/SetNextFileNameWithOverride", ReplyAction="http://tempuri.org/IServerService/SetNextFileNameWithOverrideResponse")]
        void SetNextFileNameWithOverride(string name, bool @override);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/SetNextFileNameWithOverride", ReplyAction="http://tempuri.org/IServerService/SetNextFileNameWithOverrideResponse")]
        System.Threading.Tasks.Task SetNextFileNameWithOverrideAsync(string name, bool @override);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/SetNextFileNameWithoutOverride", ReplyAction="http://tempuri.org/IServerService/SetNextFileNameWithoutOverrideResponse")]
        void SetNextFileNameWithoutOverride(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/SetNextFileNameWithoutOverride", ReplyAction="http://tempuri.org/IServerService/SetNextFileNameWithoutOverrideResponse")]
        System.Threading.Tasks.Task SetNextFileNameWithoutOverrideAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerServiceChannel : DownloadUploadTesting.ServerService.IServerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerServiceClient : System.ServiceModel.ClientBase<DownloadUploadTesting.ServerService.IServerService>, DownloadUploadTesting.ServerService.IServerService {
        
        public ServerServiceClient() {
        }
        
        public ServerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetHandlerConnectionString() {
            return base.Channel.GetHandlerConnectionString();
        }
        
        public System.Threading.Tasks.Task<string> GetHandlerConnectionStringAsync() {
            return base.Channel.GetHandlerConnectionStringAsync();
        }
        
        public System.IO.Stream DownloadFile(string fileNameAndExtension) {
            return base.Channel.DownloadFile(fileNameAndExtension);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DownloadFileAsync(string fileNameAndExtension) {
            return base.Channel.DownloadFileAsync(fileNameAndExtension);
        }
        
        public bool UploadFile(System.IO.Stream stream) {
            return base.Channel.UploadFile(stream);
        }
        
        public System.Threading.Tasks.Task<bool> UploadFileAsync(System.IO.Stream stream) {
            return base.Channel.UploadFileAsync(stream);
        }
        
        public void SetNextFileNameWithOverride(string name, bool @override) {
            base.Channel.SetNextFileNameWithOverride(name, @override);
        }
        
        public System.Threading.Tasks.Task SetNextFileNameWithOverrideAsync(string name, bool @override) {
            return base.Channel.SetNextFileNameWithOverrideAsync(name, @override);
        }
        
        public void SetNextFileNameWithoutOverride(string name) {
            base.Channel.SetNextFileNameWithoutOverride(name);
        }
        
        public System.Threading.Tasks.Task SetNextFileNameWithoutOverrideAsync(string name) {
            return base.Channel.SetNextFileNameWithoutOverrideAsync(name);
        }
    }
}
