//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServerService")]
public interface IServerService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetHandlerConnectionString", ReplyAction="http://tempuri.org/IClientService/GetHandlerConnectionStringResponse")]
    string GetHandlerConnectionString();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/DownloadFile", ReplyAction="http://tempuri.org/IClientService/DownloadFileResponse")]
    System.IO.Stream DownloadFile(string fileNameAndExtension);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/UploadFile", ReplyAction="http://tempuri.org/IServerService/UploadFileResponse")]
    bool UploadFile(System.IO.Stream stream);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/SetNextFileNameWithOverride", ReplyAction="http://tempuri.org/IServerService/SetNextFileNameWithOverrideResponse")]
    void SetNextFileNameWithOverride(string name, bool @override);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/SetNextFileNameWithoutOverride", ReplyAction="http://tempuri.org/IServerService/SetNextFileNameWithoutOverrideResponse")]
    void SetNextFileNameWithoutOverride(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServerServiceChannel : IServerService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServerServiceClient : System.ServiceModel.ClientBase<IServerService>, IServerService
{
    
    public ServerServiceClient()
    {
    }
    
    public ServerServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetHandlerConnectionString()
    {
        return base.Channel.GetHandlerConnectionString();
    }
    
    public System.IO.Stream DownloadFile(string fileNameAndExtension)
    {
        return base.Channel.DownloadFile(fileNameAndExtension);
    }
    
    public bool UploadFile(System.IO.Stream stream)
    {
        return base.Channel.UploadFile(stream);
    }
    
    public void SetNextFileNameWithOverride(string name, bool @override)
    {
        base.Channel.SetNextFileNameWithOverride(name, @override);
    }
    
    public void SetNextFileNameWithoutOverride(string name)
    {
        base.Channel.SetNextFileNameWithoutOverride(name);
    }
}
